name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        
    - name: Create application.properties
      run: echo "${{ secrets.APPLICATION }}" > src/main/resources/application.properties

    - name: Build with Gradle
      run: ./gradlew build

    - name: Docker build and push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sac-be .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/sac-be

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Stop and remove the existing container
          docker stop sac-be
          docker rm sac-be

          # Remove the existing image
          docker rmi ${{ secrets.DOCKER_USERNAME }}/sac-be
          
          # Login
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          # Pull and run the application container
          docker pull ${{ secrets.DOCKER_USERNAME }}/sac-be
          docker run -d --name sac-be -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/sac-be
          docker exec sac-be mv /usr/local/tomcat/webapps/SAC-1.0-SNAPSHOT/* /usr/local/tomcat/webapps/
          docker exec sac-be rm -rf /usr/local/tomcat/webapps/SAC-1.0-SNAPSHOT
          docker exec sac-be rm /usr/local/tomcat/webapps/SAC-1.0-SNAPSHOT.war


