name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Docker build and push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Stop and remove the existing container
          docker stop my_tomcat
          docker rm my_tomcat

          # Remove the existing image
          docker rmi ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest

          # Pull and run the application container
          docker pull ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
          docker run -d --log-driver=syslog -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest || echo "Error: Unable to start the container"
